### ISSUE TITLE
Event: FOSS Meetup March 2021

### ISSUE THREAD

**Issue by anandology** [fossunited/events#1]
#  FOSS Meetup March 2021
March 13, 2021 - 2:00PM to 4:00PM

https://fossunited.org/meetup/2021/03
https://forum.fossunited.org/t/foss-meetup-march-2021/581

# Speakers

**Ujaval Gandhi**
Founder, SpatialThoughts
[Spatialthoughts.com](https://spatialthoughts.com/)

**Omshivaprakash**
 Co-Founder Sanchi Foundation & Sanchaya
[Sanchaya.org](https://sanchaya.org/)

**Anuj Deshpande**
 Hardware Engineer
[Makerville.io](https://makerville.io/)

**Devdutt Shenoi**
GSoC scholar (batch of 2020)
[github.com/de-sh](https://github.com/de-sh/)

# Meetup Schedule

| Time  | Agenda |
| ------------- | ------------- |
| 2:00-2:15  |  Introductions |
| 2:15-2:45  | My QGIS Journey: From a User to Building a Business with Open-source Ethos by Ujaval Gandhi |
| 2:45-3:15  | Makerville - a community for hardware practitioners in India by Anuj Deshpande  |
| 3:15-3:35  | FOSS United community member discussion |
| 3:35-3:50  | FOSS empowering Kannada Language Tech projects by OmShivaPrakash  |
| 3:50-3:55  | First Commit - A platform to share and learn from FOSS contribution stories by Devdutt Shenoi   |
| 3:55-4:00  | Updates from FOSS United by Anand Chitipothu  |

TODO

# Tasks

- [x] make a poster
- [x] spread the message on social media
- [x] create event page on fossunited.org

**Comment by anandology** [comment]
Lets keep a note of all the work that goes in organizing the meetup here. We can document that in the handbook so that a new volunteers can pick it and help in running the session later.

**Comment by fossdot** [comment]
Yes. That would be helpful for new volunteers  to run later sessions

**Comment by fossdot** [comment]
**Confirmed speaker**
Anuj Deshpande
Building [MakerVille](https://makerville.io/post/why-start-a-community-for-indian-makers-5f9e601b233a6161dc5182bd) -  A community of Indian Makers

**Comment by fossdot** [comment]
OmShivaPrakash
Co-Founder, Sanchaya
[Sanchaya.org](https://sanchaya.org)

**Comment by anandology** [comment]
Ujaval Gandhi (Spacial Thoughts ) agreed to speak about QGIS. @wisharya you were copied in the email communication.

**Comment by fossdot** [comment]
> Ujaval Gandhi (Spacial Thoughts ) agreed to speak about QGIS. @wisharya you were copied in the email communication.

Yes. Missed it. Will coordinate with him now.

**Comment by anandology** [comment]
I suggest to make the session only for 2 hours this time and have a 20min
gap in the middle for discussion. Also, Ujaval want to leave early, so
please plan his session in the first or the second slot.

**Comment by fossdot** [comment]
Noted!

**Comment by fossdot** [comment]
@anandology I have added the schedule above, please let me know if we need any changes/modifications there.
