### ISSUE TITLE
Volunteers Details: FOSS Hack 2021

### ISSUE THREAD

**Issue by fossdot** [fossunited/events#10]
# Volunteers details: FOSS Hack 2021

Please share the following details by commenting on this issue:

1. Full Name
2. Short Bio (max 4-5 words)
3. Picture of yours

_Example_

Full Name: Kailash Nadh
Short Bio:  Hacker, Tinkerer, CTO at Zerodha 
Picture: Linked [here](https://nadh.in/static/images/kailash.jpg)

**Comment by de-sh** [comment]
Full Name: Devdutt Shenoi
Short Bio: Contributor, Volunteer, SE at Bytebeam
Picture: 
![1581900021534-01](https://user-images.githubusercontent.com/18750864/133393672-333df18a-8673-47ab-a127-e13b0950e941.jpeg)

**Comment by Aadya-Anil** [comment]
Full Name: Aadya Anil Kumar
Short Bio: Coding and Design, Student at GEC Thrissur
Picture: Linked [here](https://user-images.githubusercontent.com/85759627/133394647-a6444159-d6d7-4aef-bc96-879988c40369.jpg)

**Comment by DeepikaSR4** [comment]
Full Name: Deepika S R
Short Bio: Self taught UI/UX designer & Front-End Dev.
Picture : Linked 
![20210720_131853](https://user-images.githubusercontent.com/86402123/133470402-0e134912-0027-4d3b-a701-88dd46a1fdce.jpg)

**Comment by Alanmartin7007** [comment]
> Alan Martin
Short Bio : Flutter developer ; Student at Toc H Institute of science and technology
Picture : ![IMG_20200315_105211](https://user-images.githubusercontent.com/62420999/133571317-c46b3c46-79e4-44d8-a0bb-e336df0ff80e.JPG)

**Comment by 123vivekr** [comment]
Vivek R
Developer at ThoughtWorks
![image](https://user-images.githubusercontent.com/28249428/133640045-809604a2-15d8-45bb-958a-35c20e9a7c30.png)

**Comment by ajinkyabawaskar** [comment]
Ajinkya Bawaskar
Software Engineer at GlobalLogic
[Image](https://avatars.githubusercontent.com/u/24762467)

**Comment by saksham0309** [comment]
Saksham Mishra
Student at VIT Chennai | Developer | Graphic Designer
[Image](https://drive.google.com/file/d/1xsSRKJ0afRH76np8rIttwSvyHHQXQJpJ/view?usp=sharing)

**Comment by LiaPaul9895** [comment]
Full Name :Lia Paul
Short Bio  :UI/UX designer ,Student at COET  Thalassery.
![WhatsApp Image 2021-09-21 at 03 40 43 (1)](https://user-images.githubusercontent.com/89990126/134159127-01654458-b0b8-4c4d-84ad-c04a23e0b519.jpeg)

**Comment by nikochiko** [comment]
Full name: Kaustubh Maske Patil
Bio: FOSS Enthusiast, Co-Founder of Hyperlog
Picture:
![IMG_20210822_201731](https://user-images.githubusercontent.com/37668193/135749793-4c25e7a9-8220-4de5-a919-98e9fe6e211e.jpg)

**Comment by Manalimodi4** [comment]
Manali Modi
Software engineer at Global logic
![Uploading IMG_20190913_200557_307.jpg…]()

**Comment by manali4** [comment]
Manali Modi
Software engineer at Global logic
![IMG_20190913_200557_307](https://user-images.githubusercontent.com/46381118/137575580-fe040fd1-0d6c-4726-a2e6-0259c1c96f86.jpg)

**Comment by fossdot** [comment]
> Manali Modi
> Software engineer at Global logic

@ajinkyabawaskar

**Comment by nairadethya** [comment]
Adethya S Nair
![Adethya](https://user-images.githubusercontent.com/88815815/138459199-fab44304-b3d4-4124-ae78-3bafa126dbe0.png)

Developer, AI ML enthusiast,student at GEC Thrissur
``
