### ISSUE TITLE
Event: First Commit - Episode 1

### ISSUE THREAD

**Issue by anandology** [fossunited/events#6]
# First Commit - with Goutham Veeramachaneni
March 20, 2021 - 03:00-05:00PM

# Speakers

**Goutham Veeramachaneni**
Graphana Labs
https://gouthamve.dev/

**Comment by de-sh** [comment]
Projects that the speaker is associated with:
- [Prometheus/Prometheus](https://GitHub.com/Prometheus/Prometheus) 
- [cortexproject/cortex](https://GitHub.com/cortexproject/cortex)

Requirements

- [ ]  Poster
- [ ] Livestream

**Comment by de-sh** [comment]
Adding some links to interesting inputs for beginners by @gouthamve on the telegram group

- https://t.me/first_commit/604
- https://t.me/first_commit/645
